# Глобальные параметры эксперимента
experiment_name: "catboost_v1"
random_seed: 42

# Пути к директориям и файлам
paths:
  data_raw: "data/raw"
  data_processed: "data/processed"
  data_features: "data/features"
  models_experiments: "models/experiments"
  reports_figures: "reports/figures"
  reports_metrics: "reports/metrics"
  configs: "configs"
  logs: "logs"

# Параметры данных
data:
  source_path: "data/external/raw_data.csv"
  target_column: "target"
  date_column: "the_date"
  customer_id: "abs_customer"
  filters:
    min_disbursement: 500
    max_date: "2024-07-31"
    min_age: 18

# Параметры предобработки
preprocessing:
  test_size: 0.2
  val_size: 0.1
  stratify: true
  nan_threshold: 0.95
  single_value_threshold: 0.99
  date_format: "%Y-%m-%d"
  date_column: "the_date"
  target_column: "target"

# Параметры feature engineering
features:
  categorical_encoding:
    method: "frequency"  # frequency, target_encoding, one_hot
    cumsum_freq: 0.995
    handle_unknown: "ignore"
  
  numerical_scaling:
    method: "standard"  # standard, minmax, robust
    
    
  feature_selection:
    enabled: true
    method: "importance"  # importance, correlation, variance
    top_k: 100

# Параметры модели
model:
  type: "catboost"  # catboost, xgboost
  
  hyperparameters: # Model-specific hyperparameters
    catboost:
      iterations: 1000
      learning_rate: 0.1
      verbose: 100
    xgboost:
      n_estimators: 1000
      learning_rate: 0.1
      max_depth: 6
      verbosity: 0
    
# Параметры обучения
training:
  epochs: 1000
  early_stopping: 100
  cv_folds: 5
  stratified: true
  
# Параметры оптимизации гиперпараметров
hyperopt:
  enabled: false
  method: "bayesian"  # bayesian, grid, random
  n_trials: 100
  timeout: 3600
  
  search_space:
    learning_rate: [0.01, 0.3]
    # num_leaves: [10, 100]
    # feature_fraction: [0.4, 1.0]
    # bagging_fraction: [0.4, 1.0]

# Параметры оценки модели
evaluation:
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1"
    - "auc"
    - "log_loss"
  
  thresholds:
    default: 0.5
    optimal_metric: "f1"
    
  plots:
    - "confusion_matrix"
    - "roc_curve"
    - "precision_recall_curve"
    - "feature_importance"
    - "shap_summary"

# Параметры логирования
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
# Параметры для MLflow
mlflow:
  enabled: true
  tracking_uri: "http://127.0.0.1:5000"
  experiment_name: "ml_template_project"
  auto_log: true
  log_models: true
  log_artifacts: true
  artifact_location: "mlruns"  # Explicitly set artifact location for clarity