# Конфигурация для CatBoost модели

hyperparameters:
  objective: "Logloss"
  eval_metric: "AUC"
  iterations: 1000
  learning_rate: 0.1
  depth: 6
  l2_leaf_reg: 3
  border_count: 32
  feature_border_type: "GreedyLogSum"
  bagging_temperature: 1
  random_strength: 1
  verbose: False

# Параметры для поиска гиперпараметров
hyperopt_space:
  learning_rate: [0.01, 0.3]
  depth: [4, 10]
  l2_leaf_reg: [1, 10]
  border_count: [32, 255]
  bagging_temperature: [0, 10]
  random_strength: [0, 10]

# Специфичные настройки обучения
training:
  early_stopping_rounds: 100
  use_best_model: true
  plot: false