# Конфигурация для LightGBM модели

hyperparameters:
  objective: "binary"
  metric: "auc"
  boosting_type: "gbdt"
  num_leaves: 31
  learning_rate: 0.1
  feature_fraction: 0.9
  bagging_fraction: 0.8
  bagging_freq: 5
  verbose: -1
  min_data_in_leaf: 20
  lambda_l1: 0.0
  lambda_l2: 0.0
  min_gain_to_split: 0.0

# Параметры для поиска гиперпараметров
hyperopt_space:
  learning_rate: [0.01, 0.3]
  num_leaves: [10, 100]
  feature_fraction: [0.4, 1.0]
  bagging_fraction: [0.4, 1.0]
  min_data_in_leaf: [10, 50]
  lambda_l1: [0.0, 10.0]
  lambda_l2: [0.0, 10.0]

# Специфичные настройки обучения
training:
  early_stopping_rounds: 100
  verbose_eval: 50
  categorical_feature: "auto"