# Конфигурация для предобработки данных

# Параметры разбиения данных
split:
  test_size: 0.2
  val_size: 0.1
  stratify: true
  random_state: 42

# Обработка пропущенных значений
missing_values:
  # Порог для удаления столбцов с пропусками (>95% пропусков)
  drop_threshold: 0.95
  
  # Стратегии заполнения по типам данных
  fill_strategies:
    numerical:
      method: "median"  # mean, median, mode, constant
      constant_value: 0  # используется если method = constant
    
    categorical:
      method: "mode"  # mode, constant, unknown
      constant_value: "unknown"
      
    boolean:
      method: "mode"

# Обработка выбросов
outliers:
  enabled: true
  method: "iqr"  # iqr, zscore, isolation_forest
  
  # Для IQR метода
  iqr_multiplier: 1.5
  
  # Для Z-score метода
  zscore_threshold: 3
  
  # Столбцы для проверки на выбросы
  columns: ["disbursement", "income", "credit_score"]

# Удаление столбцов с низкой вариативностью
low_variance:
  # Порог для одного значения (>99% одно значение)
  single_value_threshold: 0.99
  
  # Порог для низкой вариативности
  variance_threshold: 0.01

# Валидация данных
validation:
  # Обязательные столбцы
  required_columns: ["target", "the_date", "abs_customer"]
  
  # Проверки типов данных
  data_types:
    target: "int"
    the_date: "datetime"
    abs_customer: "object"
    
  # Диапазоны значений
  value_ranges:
    age: [18, 100]
    disbursement: [0, 1000000]
    credit_score: [300, 850]

# Сохранение промежуточных результатов
save_intermediate:
  enabled: true
  save_filtered_data: true
  save_missing_report: true
  save_outliers_report: true